# This workflow deploys the IPAM Azure Function

name: Deploy-IPAM

env:
  MGMTSUBNAME: "p001mgt"  # Name of management subscription
  CONNSUBNAME: "p001con"  # Name of connectivity (network) subscription
  REGIONNAME: "uksouth"  # Azure region to deploy network resources
  REGIONID: "uks"  # Region identifier used in naming central network resources
  FUNCTIONZIPPATH: "./src/ipam.zip"  # Path to store compressed archive of function code
  ASEDEPLOY: $false  # Deploy function into an Azure Application Service Environment (ASE) - $true/$false

on:
  push:
    branches: [ none ]
  workflow_dispatch:

jobs:
  build-and-deploy-azurefunction:
    runs-on: windows-latest
    steps:
      - name: Check out repository under $GITHUB_WORKSPACE, so job can access it
        uses: actions/checkout@v2

      - name: Log on to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          
      - name: Create Function App
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $regionId = "${{ env.REGIONID }}"            
            $mgmtSubName =  "${{ env.MGMTSUBNAME }}"
            $connSubName  =  "${{ env.CONNSUBNAME }}"
            $regionName  =  "${{ env.REGIONNAME }}"
            $regionId  =  "${{ env.REGIONID }}"
            $networkAddresses = @(  "10.188.0.0/22",
                "10.188.64.0/22",
                "10.188.128.0/22",
                "10.188.192.0/22",
                "10.189.0.0/22",
                "10.189.64.0/22",
                "10.189.128.0/22",
                "10.189.192.0/22",
                "10.190.0.0/21",
                "10.190.32.0/21",
                "10.190.64.0/21",
                "10.190.96.0/21")    
            $functionZipPath  =  "${{ env.FUNCTIONZIPPATH }}"
            $aseDeploy = "${{ env.ASEDEPLOY }}"
            $subId = "${{ secrets.IPAM_SUBID }}"
            $faName = "fa-$connSubName-$regionId-ipam"
            $rgNetworkName = "rg-$connSubName-$regionId-network"
            $rgManagementName = "rg-$mgmtSubName-$regionId-management"
            
            Write-Output "Generating function zip file"
            Compress-Archive -Path ./src/function/* -DestinationPath $functionZipPath -Force
            
            Write-Output "Deploying Azure resources"
            $deploymentName = Get-Date -Format yyyyMMddHHmmss
            New-AzDeployment -Name $deploymentName -Location $regionName -TemplateFile ./src/build/ipam/ipam.bicep `
                -connSubName $connSubName -regionName $regionName -regionId $regionId -mgmtSubName $mgmtSubName `
                -rgNetworkName $rgNetworkName -rgManagementName $rgManagementName -aseDeploy $aseDeploy
          azPSVersion: latest 
