# This workflow adds IP address ranges using the IPAM function

name: IPAM-Add-Addresses

on:
  push:
    branches: [ none ]
  workflow_dispatch:

jobs:
  add-addresses:
#    runs-on: windows-latest
    runs-on: self-hosted
    steps:
      - name: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
      
      - name: Log on to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}
          
      - name: Invoke IPAM function to add address spaces
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $networkAddresses = @("10.188.0.0/22",
                                  "10.188.64.0/22",
                                  "10.188.128.0/22",
                                  "10.188.192.0/22")
            Write-Output "Adding new address spaces to IPAM"
            $uri = 'https://fa-hmrc-uksouth-ipam.azurewebsites.net/api/AddAddressSpace?code=iE2WDejqerMmOJvje/LGfn920HNQ28diICDY2yeSyDea2X8Yr1ZriA=='
            foreach ($nw in $networkAddresses) {
              Write-Output "Adding network $nw"
              $body = @{
                "NetworkAddress"=$nw
              } | ConvertTo-Json
              $params = @{
                  'Uri'         = $uri
                  'Method'      = 'POST'
                  'ContentType' = 'application/json'
                  'Body'        = $body
              }
              $Result = Invoke-RestMethod @params -ErrorAction SilentlyContinue
              Write-Output "Result of Invoke-RestMethod for network $nw :" $result
            }
          azPSVersion: latest 
