# This workflow maintains the IPAM set of available address ranges

name: Maintain-IPAM

on:
  push:
    branches: [ none ]
  workflow_dispatch:

jobs:
  build-and-deploy-azurefunction:
    runs-on: windows-latest
    steps:
      - name: Check out repository under $GITHUB_WORKSPACE, so job can access it
        uses: actions/checkout@v2

      - name: Log on to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          
      - name: Create Function App
        uses: azure/powershell@v1
        with:
          inlineScript: |           
            $nwRanges = @(@("10.160.0.0",20,"Small","Prod"),
                          @("10.161.0.0",20,"Medium","Prod"),
                          @("10.162.0.0",20,"Large","Prod"),
                          @("10.180.0.0",20,"Small","Nonprod"),
                          @("10.181.0.0",20,"Medium","Nonprod"),
                          @("10.182.0.0",20,"Large","Nonprod"))

            $mgmtSubName = "p003mgt"
            $connSubName = "p003con"
            $regionName = "uksouth"
            $regionId = "uks"
            $functionZipPath = "./elz/src/ipam.zip"
            $aseDeploy = $false
            
            $aseVnetName = "vnet-$connSubName-$regionId-01"
            $aseVnetAddress = "10.50.0.0/16"
            $aseSnetName = 'snet-ipam'
            $aseSnetAddress = "10.50.10.0/24"

            $clientId = "${{ secrets.IPAM_CLIENTID }}"
            $clientSecret = "${{ secrets.IPAM_CLIENTSECRET }}"
            $subId = "${{ secrets.IPAM_SUBID }}"
            $tenantId = (Get-AzSubscription -SubscriptionId $subId).tenantId
            $tenantId

            $faName = "fa-$connSubName-$regionId-ipam"
            $rgNetworkName = "rg-$connSubName-$regionId-ipam"
            $rgManagementName = "rg-$mgmtSubName-$regionId-management"
            
            Write-Output "Adding address spaces"
            $faId = $faObj.Id
            $addFunctionKey = (Invoke-AzResourceAction -ResourceId "$faId/functions/AddAddressSpace" -Action listkeys -Force).default
            Write-Output "Adding new address spaces to IPAM"
            if ($aseDeploy) {
              $uriAdd = 'https://' + $faName + '.ase-' + $connSubName + '-' + $regionId + '-ipam.p.azurewebsites.net/api/AddAddressSpace?code=' + $addFunctionKey
            }
            else {
              $uriAdd = 'https://' + $faName + '.azurewebsites.net/api/AddAddressSpace?code=' + $addFunctionKey
            }
            
            foreach ($nwRange in $nwRanges) {
              switch ($nwRange[2]) {
                "Small" {$count = 2; $suffix = '/23'}
                "Medium" {$count = 4; $suffix = '/22'}
                "Large" {$count = 8; $suffix = '/21'}
                Default {$count = 2; $suffix = '/23'}
              }
              $a,$b,$c,$d = $nwRange[0].Split(".")
              for ($i = 0; $i -lt $nwRange[1]; $i++) {
                $nwAddress="$a.$b.$([int]$c+($count * $i)).$d" + $suffix
                $nwEnv = $nwRange[3]
                Write-Output "Adding network $nwAddress in the $nwEnv environment"
                $body = @{
                    "NetworkAddress"=$nwAddress
                    "NwEnvironment"=$nwEnv
                } | ConvertTo-Json
                $params = @{
                    'Uri'         = $uriAdd
                    'Method'      = 'POST'
                    'ContentType' = 'application/json'
                    'Body'        = $body 
                }
                Invoke-RestMethod @params -ErrorAction SilentlyContinue
              }
            }
          azPSVersion: latest 
